<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Domain.Workshop/Domain.Workshop.csproj" />
    <ProjectReference Include="..\Domain.Vault\Domain.Vault.csproj" />
    <ProjectReference Include="..\Domain.Roster\Domain.Roster.csproj" />
    <ProjectReference Include="..\Domain.Archive\Domain.Archive.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
