<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Domains/Identity/" />
    <Folder Include="Domains/Documentation/" />
    <Folder Include="Domains/Project/Services/" />
  </ItemGroup>

</Project>
